import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import axios from 'axios';
import CommentList from './CommentList';
import CommentForm from './CommentForm';
import store from '../stores/configureStore';
import { ActionTypes as types } from '../constants';
class CommentBox extends Component {
    constructor(props) {
        super(props);

        this.state = {
            data: {}
        };
        this.handleCommentSubmit = this.handleCommentSubmit.bind(this);
        this.loadCommentsFromServer = this.loadCommentsFromServer.bind(this);
    }
    loadCommentsFromServer() {
        axios.get('/comments')
        .then((resp) => {
            store.dispatch({ type: types.RECEIVE_COMMENTS, data: resp.data })
        })
        .catch();
    };
    handleCommentSubmit(comment) {
        var comments = this.props.data;
        // Optimistically set an id on the new comment. It will be replaced by an
        // id generated by the server. In a production application you would likely
        // not use Date.now() for this and would have a more robust system in place.
        comment.Id = Date.now() + comment.Text;
        var newComments = comments.concat([comment]);
        this.setState({ data: newComments });
        var data = new FormData();
        data.append('Author', comment.Author);
        data.append('Text', comment.Text);

        var xhr = new XMLHttpRequest();
        xhr.open('post', this.props.submitUrl, true);
        xhr.onload = function () {
            this.loadCommentsFromServer();
        }.bind(this);
        xhr.send(data);
    };
    render() {
        return (
            <div className="commentBox">
                <h1>Comments</h1>
                <CommentList authData={this.props.data} />
                <CommentForm onCommentSubmit={this.handleCommentSubmit} />
            </div>
        );
    }
}
export default connect((state, props) => {
    return {
        data: state.data
    }
})(CommentBox);